### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by D-Pagey** [codeAdventureNow/LoginFormReact#1]
https://github.com/codeAdventureNow/LoginFormReact/blob/f50f62f0c043ab441bd90491d8fee2a572d68a16/src/App.js#L24

You dont need this second check

https://github.com/codeAdventureNow/LoginFormReact/blob/f50f62f0c043ab441bd90491d8fee2a572d68a16/src/App.js#L27

Typo

**Comment by codeAdventureNow** [comment]
I deleted || password === '') and corrected the typo.

I wasn't sure if you wanted me to delete all of line 24 or just this part  "password === ''.

When I tried deleting all of line 24 I would get a success message even with just 2 characters in the password.  So I left the first part of that check in:  "if (password.length < 5"
